name: build

on:
  push:
    branches:
      - 'main'
      - 'release/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build (${{ matrix.feature }}, ${{ matrix.triplet }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [ no-deps, all-lgpl, all-gpl ]
        triplet: [ x64-linux-dynamic-release, x64-windows-release, x86-windows-release ]
        include:
          - os: ubuntu
            build: ./build.sh
            triplet: x64-linux-dynamic-release
          - os: windows
            build: .\build.cmd
            triplet: x64-windows-release
          - os: windows
            build: .\build.cmd
            triplet: x86-windows-release
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://pkgs.dev.azure.com/ronaldvanmanen/_packaging/ronaldvanmanen/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
    - name: Set up DotNet NuGet Credentials
      run: >
        dotnet nuget update source azure
        --username GitHub
        --password ${{ secrets.AZURE_DEVOPS_PAT }}
        --store-password-in-clear-text
    - name: Build and Install Port Packages
      run: ${{ matrix.build }} --target build --feature ${{ matrix.feature }} --triplet ${{ matrix.triplet }}
    - name: Zip Port Packages
      run: 7z a ./artifacts/vcpkg/vcpkg-${{ matrix.feature }}-${{ matrix.triplet }}.zip ./artifacts/vcpkg/* -sdel
    - name: Upload Port Packages
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: vcpkg
        path: ./artifacts/vcpkg/vcpkg-*.zip
        if-no-files-found: error
  pack:
    name: Pack (${{ matrix.feature }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [ no-deps, all-lgpl, all-gpl ]
        include:
          - license: LGPL-2.1-or-later
            feature: no-deps
          - license: LGPL-2.1-or-later
            feature: all-lgpl
          - license: GPL-2.0-or-later
            feature: all-gpl
    needs: [ build ]
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Download Port Packages
      uses: actions/download-artifact@v3
      with:
        name: vcpkg
        path: ./artifacts/vcpkg
    - name: Unzip Port Packages
      run: 7z x ./artifacts/vcpkg/vcpkg-*.zip -o ./artifacts/vcpkg/ -y
    - name: Set up DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://pkgs.dev.azure.com/ronaldvanmanen/_packaging/ronaldvanmanen/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
    - name: Set up DotNet NuGet Credentials
      run: >
        dotnet nuget update source azure
        --username GitHub
        --password ${{ secrets.AZURE_DEVOPS_PAT }}
        --store-password-in-clear-text
      shell: bash
    - name: Build NuGet Packages.
      run: >
        ./build.sh --target pack
        --feature ${{ matrix.feature }}
        --triplet x64-linux-dynamic-release
        --triplet x64-windows-release
        --triplet x86-windows-release
        --license ${{ matrix.license }}
      shell: bash
    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: ./artifacts/nuget/installed/**/*
        if-no-files-found: error
  publish-azure:
    name: Publish on Azure
    runs-on: ubuntu-latest
    needs: [ pack ]
    steps:
    - name: Download NuGet Packages
      uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ./artifacts/nuget/installed
    - name: Set up DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://pkgs.dev.azure.com/ronaldvanmanen/_packaging/ronaldvanmanen/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
    - name: Push NuGet packages
      run: >
        dotnet nuget push "./artifacts/nuget/installed/**/*.nupkg"
        --api-key AzureDevOps
        --skip-duplicate
      shell: bash
  publish-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [ pack ]
    steps:
    - name: Download NuGet Packages
      uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ./artifacts/nuget/installed
    - name: Set up DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/ronaldvanmanen/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push NuGet Packages
      run: >
        dotnet nuget push "./artifacts/nuget/installed/**/*.nupkg"
        --source "https://nuget.pkg.github.com/ronaldvanmanen/index.json"
        --api-key ${{ secrets.GITHUB_TOKEN }}
        --skip-duplicate
      shell: bash
