name: build

on:
  push:
    branches:
      - 'main'
      - 'release/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-multiplatform:
    name: Build Multiplatform
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'
    - run: .\scripts\build-multiplatform.cmd
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: .\artifacts\packages\**\*
        if-no-files-found: error
  publish-artifacts-on-azure:
    name: Publish Artifacts on Azure
    runs-on: ubuntu-latest
    needs: [ build-multiplatform ]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: ./artifacts
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://pkgs.dev.azure.com/ronaldvanmanen/FFmpegSharp/_packaging/FFmpegSharp/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
    - run: dotnet nuget push "./artifacts/**/*.nupkg" --api-key AzureDevOps --skip-duplicate
  publish-artifacts-on-github:
    name: Publish Artifacts on GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write    
    needs: [ build-multiplatform ]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: ./artifacts
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/ronaldvanmanen/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dotnet nuget push "./artifacts/**/*.nupkg" --source "https://nuget.pkg.github.com/ronaldvanmanen/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate