name: build

on:
  push:
    branches:
      - 'main'
      - 'release/**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-linux:
    name: Build (${{ matrix.feature }}, ${{ matrix.triplet }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ no-deps ]
        triplet: [ x64-linux-dynamic-release ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://pkgs.dev.azure.com/ronaldvanmanen/_packaging/ronaldvanmanen/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'
    - run: sudo apt-get update
      shell: bash
    - run: sudo apt-get install nasm
      shell: bash
    - run: >
        dotnet nuget update source azure
        --username GitHub
        --password ${{ secrets.AZURE_DEVOPS_PAT }}
        --store-password-in-clear-text
      shell: bash
    - run: ./build.sh --target build --feature ${{ matrix.feature }} --triplet ${{ matrix.triplet }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: vcpkg
        path: ./artifacts/vcpkg/${{ matrix.feature }}/${{ matrix.triplet }}/installed/${{ matrix.triplet }}/**/*
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: vcpkg-${{ matrix.feature }}-${{ matrix.triplet }}
        path: ./artifacts/vcpkg/**/*
        if-no-files-found: error
  build-windows:
    name: Build (${{ matrix.feature }}, ${{ matrix.triplet }})
    runs-on: windows-latest
    strategy:
      matrix:
        feature: [ no-deps ]
        triplet: [ x64-windows-release, x86-windows-release ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://pkgs.dev.azure.com/ronaldvanmanen/_packaging/ronaldvanmanen/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
    - run: >
        dotnet nuget update source azure
        --username GitHub
        --password ${{ secrets.AZURE_DEVOPS_PAT }}
        --store-password-in-clear-text
      shell: cmd
    - run: .\build.cmd --target build --feature ${{ matrix.feature }} --triplet ${{ matrix.triplet }}
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: vcpkg
        path: .\artifacts\vcpkg\${{ matrix.feature }}\${{ matrix.triplet }}\installed\${{ matrix.triplet }}\**\*
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: vcpkg-${{ matrix.feature }}-${{ matrix.triplet }}
        path: .\artifacts\vcpkg\**\*
        if-no-files-found: error
  pack:
    name: Pack (${{ matrix.feature }})
    runs-on: windows-latest
    strategy:
      matrix:
        feature: [ no-deps ]
    needs: [ build-linux, build-windows ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/download-artifact@v3
      with:
        name: vcpkg
        path: .\artifacts\vcpkg
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'
    - run: >
        dotnet nuget update source azure
        --username GitHub
        --password ${{ secrets.AZURE_DEVOPS_PAT }}
        --store-password-in-clear-text
      shell: cmd
    - run: >
        .\build.cmd --target pack
        --feature ${{ matrix.feature }}
        --triplet x64-linux-dynamic-release
        --triplet x64-windows-release
        --triplet x86-windows-release
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: .\artifacts\nuget\installed\**\*
        if-no-files-found: error
  publish-azure:
    name: Publish on Azure
    runs-on: ubuntu-latest
    needs: [ pack ]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ./artifacts/nuget/installed
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://pkgs.dev.azure.com/ronaldvanmanen/_packaging/ronaldvanmanen/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }}
    - run: >
        dotnet nuget push "./artifacts/nuget/installed/**/*.nupkg"
        --api-key AzureDevOps
        --skip-duplicate
      shell: bash
  publish-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [ pack ]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ./artifacts/nuget/installed
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/ronaldvanmanen/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: >
        dotnet nuget push "./artifacts/nuget/installed/**/*.nupkg"
        --source "https://nuget.pkg.github.com/ronaldvanmanen/index.json"
        --api-key ${{ secrets.GITHUB_TOKEN }}
        --skip-duplicate
      shell: bash
